"""add expires_at to meet_requests

Revision ID: fbaf08a8faec
Revises: add_session_user_audit
Create Date: 2026-02-27 09:52:53.696715

"""

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision = "fbaf08a8faec"
down_revision = "add_session_user_audit"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "audit_events",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.drop_index(op.f("ix_audit_events_session_id"), table_name="audit_events")
    op.drop_index(op.f("ix_audit_events_user_id"), table_name="audit_events")
    op.drop_constraint(op.f("fk_audit_events_session_id"), "audit_events", type_="foreignkey")
    op.drop_constraint(op.f("fk_audit_events_user_id"), "audit_events", type_="foreignkey")
    op.create_foreign_key(None, "audit_events", "users", ["user_id"], ["id"])
    op.create_foreign_key(None, "audit_events", "sessions", ["session_id"], ["id"])
    op.add_column("meet_requests", sa.Column("expires_at", sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("meet_requests", "expires_at")
    op.drop_constraint(None, "audit_events", type_="foreignkey")
    op.drop_constraint(None, "audit_events", type_="foreignkey")
    op.create_foreign_key(
        op.f("fk_audit_events_user_id"),
        "audit_events",
        "users",
        ["user_id"],
        ["id"],
        ondelete="SET NULL",
    )
    op.create_foreign_key(
        op.f("fk_audit_events_session_id"),
        "audit_events",
        "sessions",
        ["session_id"],
        ["id"],
        ondelete="SET NULL",
    )
    op.create_index(op.f("ix_audit_events_user_id"), "audit_events", ["user_id"], unique=False)
    op.create_index(op.f("ix_audit_events_session_id"), "audit_events", ["session_id"], unique=False)
    op.alter_column(
        "audit_events",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=True,
        existing_server_default=sa.text("now()"),
    )
    # ### end Alembic commands ###
